---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: molecule-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    published_ports:
      - 0.0.0.0:8081:80/tcp

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: default
      result_format: yaml

verifier:
  name: ansible
