[webservers]
web01 ansible_host=10.10.1.11
web02 ansible_host=10.10.1.12

[databases]
db01 ansible_host=10.10.2.11
db02 ansible_host=10.10.2.12

[loadbalancers]
lb01 ansible_host=10.10.3.11
lb02 ansible_host=10.10.3.12

[development]
dev01 ansible_host=10.20.1.11
dev02 ansible_host=10.20.1.12

[production:children]
webservers
databases
loadbalancers

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
