---
- name: Validate Apache configuration
  ansible.builtin.command:
    cmd: /usr/sbin/apache2ctl configtest
  changed_when: false
  listen:
    - Restart Apache
    - Reload Apache

- name: Restart Apache
  ansible.builtin.systemd_service:
    name: apache2
    state: restarted

- name: Reload Apache
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
